# =============================================================================
# Contextual Music Crafter - Configuration
# =============================================================================
# This file controls model settings, musical parameters, and instruments.
# All comments are informational; you can keep or remove them as you like.

# Meta notes (informational)
# - Comments are preserved when using music_crafter.py (ruamel.yaml round-trip).
# - Provide a list under api_key to enable automatic key rotation on 429/quota.
# - For long runs, song_generator.py can resume with --resume-file.
# - See README for advanced notes and troubleshooting.

# -----------------------------------------------------------------------------
# API Configuration
# -----------------------------------------------------------------------------
# You can provide a single key (string) or multiple keys (list) for key rotation.

api_key:
  - "YOUR_GOOGLE_AI_API_KEY_1"
  #- "YOUR_GOOGLE_AI_API_KEY_2"
  #- "YOUR_GOOGLE_AI_API_KEY_3"
  #- "YOUR_GOOGLE_AI_API_KEY_4"
  #- "YOUR_GOOGLE_AI_API_KEY_5"

# Model selection
# Recommended options: "gemini-2.5-pro" (highest quality), "gemini-2.5-flash" (faster/cheaper)
model_name: gemini-2.5-pro

# Sampling temperature (0.0 = deterministic, 2.0 = very creative)
# Note: Values closer to 0 tend to be more reliable/consistent but less creative/playful;
#       higher values increase novelty and variation at the cost of stability.
temperature: 0

# -----------------------------------------------------------------------------
# Automation Settings
# -----------------------------------------------------------------------------
# Enable expressive MIDI data. 0 = disabled, 1 = enabled
automation_settings:
  # Pitch Bend: slides and vibrato
  use_pitch_bend: 0

  # Sustain Pedal (CC64): legato/hold for pianos and pads
  use_sustain_pedal: 0

  # Control Change (CC) curves: filter/volume/pan etc.
  use_cc_automation: 0

  # Allowed CC numbers if CC automation is enabled
  # 1: Modulation, 10: Pan, 11: Expression, 74: Filter Cutoff
  allowed_cc_numbers: [1, 10, 11, 74]

# -----------------------------------------------------------------------------
# Musical Parameters
# -----------------------------------------------------------------------------
# Free-form description to guide the composition
inspiration: |-
  Generate a track that captures the essence of a generic house music track. The rhythmic foundation should feature a consistent four-on-the-floor kick on every quarter note, reinforced by a clap on beats two and four, and a driving pattern of closed 16th-note hi-hats, often with an open hi-hat on the second and fourth upbeat of each bar. A simple, repetitive two or four-bar bassline, predominantly using 8th notes, should establish the harmonic movement, typically outlining root notes and fifths of a diatonic major or minor scale with consistent note velocities. Over this, introduce a sustained chord progression, often four or eight bars in length, played with moderate velocities (e.g., 80-100), accompanied by a short, catchy melodic motif, repeating every two or four bars, using simple 8th or 16th-note figures. The structure should build through repetition, subtle additions of percussive elements like shakers or congas playing off-beat 16th notes, and occasional removal of elements to create tension and release, maintaining a steady tempo throughout.

# Main style/genre
genre: House

# Tempo in BPM
bpm: 125

# Key and scale (e.g., "C major", "A minor", "F# dorian")
key_scale: C major

# Available scales: "major", "ionian", "minor", "natural minor", "aeolian", "harmonic minor", "melodic minor",
# "dorian", "phrygian", "lydian", "mixolydian", "locrian", "major pentatonic", "minor pentatonic",
# "chromatic", "whole tone", "diminished", "augmented", "byzantine", "hungarian minor", "persian",
# "arabic", "jewish", "ahava raba", "blues", "major blues"

# -----------------------------------------------------------------------------
# Generation & Performance Settings
# -----------------------------------------------------------------------------

# Maximum tokens per model response (higher = longer outputs, more cost).
# Increase if responses get truncated; decrease to save tokens.
max_output_tokens: 65536

# Previous-themes context window:
# -1 = dynamic (use as much as fits), 0 = none, >0 = fixed number of recent themes
context_window_size: -1

# Call-and-response mode for melodic instruments (0/1).
# Eligible roles: bass, chords, arp, guitar, lead, melody, vocal
use_call_and_response: 0

# Number of complete songs per run
number_of_iterations: 1

# Time signature
time_signature:
  beats_per_bar: 4
  beat_value: 4

# -----------------------------------------------------------------------------
# Instrument Definitions
# -----------------------------------------------------------------------------
# Order defines generation order. Each entry needs name, program_num, and role.
# MIDI channel policy: drums/percussion use Channel 10 (index 9). Melodic parts
# are assigned sequentially across remaining channels, skipping 10.
# Available roles (selection): drums, kick_and_snare, percussion, sub_bass, bass,
# pads, atmosphere, texture, chords, harmony, arp, guitar, lead, melody, vocal,
# fx, complementary

# Available Roles:
#   - "drums"
#   - "kick_and_snare"
#   - "percussion"
#   - "sub_bass"
#   - "bass"
#   - "pads"
#   - "atmosphere"
#   - "texture"
#   - "chords"
#   - "harmony"
#   - "arp"
#   - "guitar"
#   - "lead"
#   - "melody"
#   - "vocal"
#   - "fx"
#   - "complementary"

instruments:
  - name: House Kick & Clap
    program_num: 119
    role: kick_and_snare
  - name: Driving Hi-Hats
    program_num: 119
    role: percussion
  - name: Classic House Bassline
    program_num: 39
    role: bass
  - name: Warm Chord Pad
    program_num: 90
    role: pads
  - name: Catchy Synth Lead
    program_num: 82
    role: lead
  - name: Off-Beat Percussion
    program_num: 114
    role: percussion

# -----------------------------------------------------------------------------
# Troubleshooting (quick reference)
# -----------------------------------------------------------------------------
# - 429 / quota exceeded: rotate API keys or pause and resume later.
# - 5xx internal errors/timeouts: retry later; switching model (e.g., gemini-2.5-flash) can help.
# - Empty/invalid response: usually transient under load; try again or lower temperature.

# --- MIDI Technical Reference (informational) ---
# General MIDI Channel Assignments:
# - Channel 10 (index 9): Drums & Percussion.
# - Channels 1-9 & 11-16: Melodic & Tonal Instruments. Assigned sequentially, skipping channel 10.

# ALL MIDI Program Numbers

# 1-8: Pianos
# 1. Acoustic Grand Piano
# 2. Bright Acoustic Piano
# 3. Electric Grand Piano
# 4. Honky-Tonk Piano
# 5. Electric Piano 1
# 6. Electric Piano 2
# 7. Harpsichord
# 8. Clavinet

# 9-16: Chromatic Percussion
# 9. Celesta
# 10. Glockenspiel
# 11. Music Box
# 12. Vibraphone
# 13. Marimba
# 14. Xylophone
# 15. Tubular Bells
# 16. Dulcimer

# 17-24: Organs
# 17. Drawbar Organ
# 18. Percussive Organ
# 19. Rock Organ
# 20. Church Organ
# 21. Reed Organ
# 22. Accordion
# 23. Harmonica
# 24. Tango Accordion

# 25-32: Guitars
# 25. Acoustic Guitar (nylon)
# 26. Acoustic Guitar (steel)
# 27. Electric Guitar (jazz)
# 28. Electric Guitar (clean)
# 29. Electric Guitar (muted)
# 30. Overdriven Guitar
# 31. Distortion Guitar
# 32. Guitar Harmonics

# 33-40: Basses
# 33. Acoustic Bass
# 34. Electric Bass (finger)
# 35. Electric Bass (pick)
# 36. Fretless Bass
# 37. Slap Bass 1
# 38. Slap Bass 2
# 39. Synth Bass 1
# 40. Synth Bass 2

# 41-48: Strings
# 41. Violin
# 42. Viola
# 43. Cello
# 44. Contrabass
# 45. Tremolo Strings
# 46. Pizzicato Strings
# 47. Orchestral Harp
# 48. Timpani

# 49-56: Ensemble
# 49. String Ensemble 1
# 50. String Ensemble 2
# 51. SynthStrings 1
# 52. SynthStrings 2
# 53. Choir Aahs
# 54. Voice Oohs
# 55. Synth Voice
# 56. Orchestra Hit

# 57-64: Brass
# 57. Trumpet
# 58. Trombone
# 59. Tuba
# 60. Muted Trumpet
# 61. French Horn
# 62. Brass Section
# 63. Synth Brass 1
# 64. Synth Brass 2

# 65-72: Reed
# 65. Soprano Sax
# 66. Alto Sax
# 67. Tenor Sax
# 68. Baritone Sax
# 69. Oboe
# 70. English Horn
# 71. Bassoon
# 72. Clarinet

# 73-80: Pipe
# 73. Piccolo
# 74. Flute
# 75. Recorder
# 76. Pan Flute
# 77. Blown Bottle
# 78. Shakuhachi
# 79. Whistle
# 80. Ocarina

# 81-88: Synth Lead
# 81. Lead 1 (square)
# 82. Lead 2 (sawtooth)
# 83. Lead 3 (calliope)
# 84. Lead 4 (chiff)
# 85. Lead 5 (charang)
# 86. Lead 6 (voice)
# 87. Lead 7 (fifths)
# 88. Lead 8 (bass + lead)

# 89-96: Synth Pad
# 89. Pad 1 (new age)
# 90. Pad 2 (warm)
# 91. Pad 3 (polysynth)
# 92. Pad 4 (choir)
# 93. Pad 5 (bowed)
# 94. Pad 6 (metallic)
# 95. Pad 7 (halo)
# 96. Pad 8 (sweep)

# 97-104: Synth Effects
# 97. FX 1 (rain)
# 98. FX 2 (soundtrack)
# 99. FX 3 (crystal)
# 100. FX 4 (atmosphere)
# 101. FX 5 (brightness)
# 102. FX 6 (goblins)
# 103. FX 7 (echoes)
# 104. FX 8 (sci-fi)

# 105-112: Ethnic
# 105. Sitar
# 106. Banjo
# 107. Shamisen
# 108. Koto
# 109. Kalimba
# 110. Bagpipe
# 111. Fiddle
# 112. Shanai

# 113-120: Percussive
# 113. Tinkle Bell
# 114. Agogo
# 115. Steel Drums
# 116. Woodblock
# 117. Taiko Drum
# 118. Melodic Tom
# 119. Synth Drum
# 120. Reverse Cymbal

# 121-128: Sound Effects
# 121. Guitar Fret Noise
# 122. Breath Noise
# 123. Seashore
# 124. Bird Tweet
# 125. Telephone Ring
# 126. Helicopter
# 127. Applause
# 128. Gunshot
