# API Configuration
# IMPORTANT: Enter your Google AI API key below.
# To get a key, visit https://aistudio.google.com/app/apikey
api_key: "YOUR_API_KEY_HERE"
model_name: "gemini-1.5-flash" # Recommended model. Others like "gemini-1.5-pro" also work.

# Musical Base Settings
inspiration: "Vini Vici, Astrix, Liquid Soul" # Artists for style inspiration
genre: "psytrance"                          # Music genre
bpm: 140                                    # Tempo in beats per minute
key_scale: "E minor"                        # Key and scale (e.g., "C# major", "F phrygian")

# The script automatically calculates technical values like 'root_note' and 'scale_type'
# from the 'key_scale' setting above. You do not need to set them manually.
time_signature:
  beats_per_bar: 4
  beat_value: 4

# Instrument Configuration
# Define your instruments. The name (e.g., "lead") is for the AI.
# The number is the General MIDI program number (1-128).
# For drums, use a name containing "drum". The program number is ignored
# as it will be assigned to the standard MIDI drum channel (10).
instruments:
  lead: 81    # Synth Lead
  bass: 38    # Synth Bass
  pad: 90     # Pad (polysynth)
  arp: 99     # FX 3 (crystal)
  drums: 10   # This number is ignored for drums but must be present.
  acid: 82    # Lead 2 (sawtooth) for 303-style lines

# --- Advanced Generation Control ---

# Defines the order in which instrument tracks are generated.
# This is crucial as each track is composed with knowledge of the previous ones.
# A logical order for the genre is recommended (e.g., rhythm section first).
generation_order:
  - "drums"
  - "bass"
  - "pad"
  - "arp"
  - "acid"
  - "lead" 